export const SET_USER = "SET_USER";
export const CLEAR_USER = "CLEAR_USER";
//CHANNEL
export const SET_CURRENT_CHANNEL = "SET_CURRENT_CHANNEL";
export const SET_PRIVATE_CHANNEL = "SET_PRIVATE_CHANNEL";
// MESSAGE
export const ADD_MESSAGES = "ADD_MESSAGES";
// USERS
export const ADD_USERS = "ADD_USERS";
